### ISSUE TITLE
Script quits if code fails to compile

### ISSUE THREAD

**Issue by kyle-rader** [kyle-rader/cmd-line-grader#2]
@RadicalZephyr 
Adding the `set -e` has good reason behind it, but now this means if a student's source code does not compile - it halts the whole script.  I want to ignore this, log the compiler errors in the file and press onward.  I have commented it out for current use.  Is there an elegant way around this?

**Comment by RadicalZephyr** [comment]
The proper way to do it is to explicitly expect that it may fail by putting
it in an if statement or using the || operator. This will cause it not to
quit the script even if it fails.  If nothing actually needs to be done,
then the most idiomatic way to eat the error silently would be this
'<command> || :'

The colon is the null command, just does nothing.

On Wednesday, March 4, 2015, Kyle W. Rader notifications@github.com wrote:

> @RadicalZephyr https://github.com/RadicalZephyr
> Adding the set -e has good reason behind it, but now this means if a
> student's source code does not compile - it halts the whole script. I want
> to ignore this, log the compiler errors in the file and press onward. I
> have commented it out for current use. Is there an elegant way around this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kyle-rader/cmd-line-grader/issues/2.

## 

Geoff (from mobile)

Nothing is ever easy.

**Comment by kyle-rader** [comment]
Aha, thank you very much sir!
